# Generated by Django 5.0.7 on 2024-07-14 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='notemodel',
            table='user',
        ),
    ]
