# Generated by Django 5.0.7 on 2024-07-13 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notemodel',
            options={'ordering': ['username']},
        ),
        migrations.AlterModelTable(
            name='notemodel',
            table='notes',
        ),
    ]
