# Generated by Django 5.0.7 on 2024-07-14 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_notemodel_options_alter_notemodel_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='notemodel',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
