# Generated by Django 5.0.7 on 2024-07-15 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_notemodel_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notemodel',
            options={'ordering': ['mainuser']},
        ),
        migrations.AddField(
            model_name='notemodel',
            name='mainpass',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='notemodel',
            name='mainuser',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='notemodel',
            name='password',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='notemodel',
            name='username',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
