# Generated by Django 5.0.7 on 2024-07-14 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_notemodel_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notemodel',
            name='id',
        ),
        migrations.AlterField(
            model_name='notemodel',
            name='username',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
