# Generated by Django 5.0.7 on 2024-07-16 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_notemodel_id_alter_notemodel_mainuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='notemodel',
            name='id',
            field=models.BigAutoField(auto_created=True, default='saik', primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notemodel',
            name='mainpass',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='notemodel',
            name='mainuser',
            field=models.CharField(default=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='notemodel',
            name='password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='notemodel',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
