# Generated by Django 5.0.7 on 2024-07-14 13:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_notemodel_id_alter_notemodel_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='notemodel',
            name='id',
            field=models.UUIDField(default=uuid.uuid3, editable=False),
        ),
    ]
