# Generated by Django 5.0.7 on 2024-07-14 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_notemodel_id'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='notemodel',
            table='public"."notes',
        ),
    ]
