# Generated by Django 5.0.7 on 2024-07-14 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_notemodel_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='notemodel',
            table='notes',
        ),
    ]
