# Generated by Django 5.0.7 on 2024-07-14 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_notemodel_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notemodel',
            name='id',
        ),
        migrations.AlterField(
            model_name='notemodel',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
