# Generated by Django 5.0.7 on 2024-07-14 14:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_remove_notemodel_id_alter_notemodel_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='notemodel',
            name='id',
            field=models.UUIDField(default=uuid.uuid3, editable=False),
        ),
    ]
