# Generated by Django 5.0.7 on 2024-07-14 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_notemodel_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notemodel',
            name='description',
        ),
        migrations.AlterField(
            model_name='notemodel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='notemodel',
            name='username',
            field=models.CharField(max_length=20),
        ),
    ]
