# Generated by Django 5.0.7 on 2024-07-14 14:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_notemodel_description_alter_notemodel_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notemodel',
            name='id',
            field=models.UUIDField(default=uuid.uuid3, editable=False, primary_key=True, serialize=False),
        ),
    ]
