# Generated by Django 5.0.7 on 2024-07-14 14:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_alter_notemodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notemodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e14ae6c1-5fdf-3c24-951b-c415037d7425'), editable=False, primary_key=True, serialize=False),
        ),
    ]
