# Generated by Django 5.0.7 on 2024-07-14 14:25

import myapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_alter_notemodel_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='notemodel',
            name='uuid_field',
            field=models.UUIDField(default=myapp.models.generate_uuid3, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='notemodel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
